### ISSUE TITLE
Staticmap not included in export, but ok in preview.

### ISSUE THREAD

**Issue by benliq** [uber/hubble.gl#30]
Hi,
While trying the "trips" example, everything is working fine, data layers, trips are animated and the underlaying static map is displayed.
When i run a "Preview" render it's ok too.
But when i export to gif or any other format, only the layers are displayed, but not the staticmap in the background.
How can i get the map to be rendered too?
Thanks a lot for your help

**Comment by chrisgervang** [comment]
Hi @benliq the underlying issue was resolved in https://github.com/uber/hubble.gl/pull/31 and I have a Guide Book planned to help make Mapbox basemap integration easier in other apps. 

The issue stems from Mapbox and Deck.gl by default rendering in two canvases, and hubble capturing only one canvas (for performance reason, primarily - otherwise it would need to stitch PNGs together for every frame, which is costly). The solution is to use the `@deck.gl/mapbox` package to fuse the two webgl contexts together into one canvas.

An alternate workaround is to use deck.gl's `MVTLayer` or `TileLayer` to do basemap rendering in native layers.
